/* 
    This file is wholely generated by ChatGPT.
    It is intended to seed a database for an art-focused social media platform using Prisma ORM.
    The script creates users, posts with artistic images, likes, comments, and follow relationships.
    Image URLs are sourced from Unsplash and Picsum to ensure high-quality artistic content.
*/

import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

// Art-related search terms for Unsplash
const artCategories = [
  "painting",
  "sculpture",
  "digital-art",
  "illustration",
  "watercolor",
  "abstract-art",
  "pottery",
  "ceramics",
  "woodworking",
  "textile-art",
  "photography",
  "mixed-media",
  "printmaking",
  "calligraphy",
  "street-art",
  "oil-painting",
  "acrylic-painting",
  "charcoal-drawing",
  "pencil-sketch",
  "collage",
];

const artMediums = [
  "Oil Paint",
  "Watercolor",
  "Acrylic",
  "Digital",
  "Pencil",
  "Charcoal",
  "Pastel",
  "Ink",
  "Mixed Media",
  "Sculpture",
  "Ceramics",
  "Textile",
  "Photography",
  "Printmaking",
  "Collage",
];

// Artistic image sources using Unsplash (free, no API key needed)
function getArtisticImageUrl(index, category) {
  const categories = [
    "art",
    "painting",
    "abstract",
    "illustration",
    "sculpture",
    "drawing",
    "watercolor",
    "creative",
    "artistic",
    "design",
  ];
  const cat = category || categories[index % categories.length];
  // Using Unsplash Source API for random artistic images
  return `https://source.unsplash.com/800x600/?${cat},artwork&sig=${index}`;
}

// Alternative: Use Picsum for reliable images with artistic feel
function getPicsumImageUrl(index) {
  // Picsum provides high-quality images
  return `https://picsum.photos/seed/${index}/800/600`;
}

// Use Lorem Picsum with specific artistic image IDs
function getReliableArtImageUrl(index) {
  // These are curated artistic-looking images from Picsum
  const artisticIds = [
    1, 10, 11, 14, 15, 16, 17, 19, 20, 22, 24, 25, 26, 27, 28, 29, 30, 31, 32,
    33, 34, 35, 36, 37, 39, 40, 41, 42, 43, 44, 45, 47, 48, 49, 50, 51, 52, 53,
    54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
    73, 74, 75, 76, 77, 78, 79, 80, 82, 83, 84, 85, 87, 88, 89, 90, 91, 92, 93,
    94, 95, 96, 98, 99, 100, 101, 102, 103, 104, 106, 107, 108, 109, 110, 111,
    112, 113, 114, 115, 116, 117, 118, 119,
  ];
  const id = artisticIds[index % artisticIds.length];
  return `https://picsum.photos/id/${id}/800/600`;
}

const firstNames = [
  "Emma",
  "Liam",
  "Olivia",
  "Noah",
  "Ava",
  "Ethan",
  "Sophia",
  "Mason",
  "Isabella",
  "William",
  "Mia",
  "James",
  "Charlotte",
  "Benjamin",
  "Amelia",
  "Lucas",
  "Harper",
  "Henry",
  "Evelyn",
  "Alexander",
  "Luna",
  "Daniel",
  "Camila",
  "Michael",
  "Gianna",
  "Sebastian",
  "Aria",
  "Jack",
  "Penelope",
  "Owen",
  "Layla",
  "Theodore",
  "Chloe",
  "Aiden",
  "Riley",
  "Samuel",
  "Zoey",
  "Ryan",
  "Nora",
  "Leo",
  "Lily",
  "Mateo",
  "Eleanor",
  "David",
  "Hannah",
  "Joseph",
  "Lillian",
  "John",
  "Addison",
  "Wyatt",
];

const lastNames = [
  "Smith",
  "Johnson",
  "Williams",
  "Brown",
  "Jones",
  "Garcia",
  "Miller",
  "Davis",
  "Rodriguez",
  "Martinez",
  "Hernandez",
  "Lopez",
  "Gonzalez",
  "Wilson",
  "Anderson",
  "Thomas",
  "Taylor",
  "Moore",
  "Jackson",
  "Martin",
  "Lee",
  "Perez",
  "Thompson",
  "White",
  "Harris",
  "Sanchez",
  "Clark",
  "Ramirez",
  "Lewis",
  "Robinson",
  "Walker",
  "Young",
  "Allen",
  "King",
  "Wright",
  "Scott",
  "Torres",
  "Nguyen",
  "Hill",
  "Flores",
  "Green",
  "Adams",
  "Nelson",
  "Baker",
  "Hall",
  "Rivera",
  "Campbell",
  "Mitchell",
  "Carter",
  "Roberts",
];

const artistBios = [
  "Passionate about creating art that tells stories. I find inspiration in everyday moments and transform them into visual poetry.",
  "Mixed media artist exploring the boundaries between traditional and digital art. Coffee addict and cat lover.",
  "Self-taught artist with a love for bold colors and abstract expressions. Every piece is a journey into the unknown.",
  "Fine arts graduate with a focus on contemporary sculpture. I believe art should provoke thought and emotion.",
  "Digital artist and illustrator. I create worlds that exist only in imagination and bring them to life on screen.",
  "Traditional painter turned digital creator. My work bridges the gap between classic techniques and modern technology.",
  "Street artist and muralist. I believe art belongs to everyone and should be accessible in public spaces.",
  "Watercolor enthusiast capturing the beauty of nature. Each painting is a meditation on light and color.",
  "Ceramic artist crafting functional art for everyday life. I find peace in the wheel and magic in the kiln.",
  "Printmaker and book artist. I love the tactile nature of paper and ink and the stories they can tell together.",
  "Photographer with a passion for portraits. I capture the essence of people through my lens.",
  "Textile artist weaving stories into fabric. My work explores cultural heritage and personal identity.",
  "Calligrapher and lettering artist. I believe words are art, and how we write them matters.",
  "Collage artist finding beauty in discarded materials. One person's trash is another's masterpiece.",
  "Oil painter specializing in landscapes. I chase the light and try to capture moments of natural beauty.",
];

const postTitles = [
  "Morning Light Study",
  "Abstract Dreams",
  "Urban Exploration",
  "Nature's Palette",
  "Midnight Thoughts",
  "Color Explosion",
  "Quiet Moments",
  "Dancing Shadows",
  "Ocean Whispers",
  "Mountain Serenity",
  "City Lights",
  "Garden Dreams",
  "Autumn Reflections",
  "Winter Solitude",
  "Spring Awakening",
  "Summer Vibes",
  "Ethereal Beauty",
  "Raw Emotion",
  "Timeless Classic",
  "Modern Twist",
  "Vintage Soul",
  "Future Vision",
  "Inner Peace",
  "Wild Spirit",
  "Gentle Touch",
  "Bold Statement",
  "Subtle Grace",
  "Vibrant Energy",
  "Calm Waters",
  "Stormy Skies",
  "Golden Hour",
  "Blue Period",
  "Red Passion",
  "Green Envy",
  "Purple Haze",
  "Silver Lining",
  "Copper Tones",
  "Marble Dreams",
  "Glass Reflections",
  "Paper Thin",
  "Stone Cold",
  "Silk Smooth",
  "Velvet Touch",
  "Cotton Soft",
  "Metal Edge",
  "Wood Grain",
  "Clay Formation",
  "Ink Flow",
  "Pencil Lines",
  "Brush Strokes",
];

const postDescriptions = [
  "Experimenting with new techniques today. Really happy with how the colors blend together in this piece.",
  "This piece took me three weeks to complete. Every detail was carefully considered and executed.",
  "Inspired by a dream I had last night. Sometimes the best ideas come when we're not looking for them.",
  "Back to basics with this one. Sometimes simplicity speaks louder than complexity.",
  "Pushing my boundaries with this experimental piece. Not sure if I love it or hate it yet!",
  "A tribute to my favorite artist. Standing on the shoulders of giants.",
  "Created this during a live session. The energy of the audience really influenced the final result.",
  "My entry for the upcoming exhibition. Fingers crossed!",
  "Just playing around with materials I found in my studio. Happy accidents happen!",
  "This piece represents my journey over the past year. So much growth and change.",
  "Commissioned piece for a lovely client. It was a joy to bring their vision to life.",
  "Exploring themes of identity and belonging in this series.",
  "Nature continues to be my greatest teacher. Observed these patterns during my morning walk.",
  "Collaboration with a fellow artist. Two minds creating something neither could alone.",
  "First attempt at this technique. Learning is a lifelong process.",
  "Revisiting an old piece with fresh eyes. Sometimes distance gives clarity.",
  "Created this piece listening to my favorite album on repeat. Music and art are deeply connected.",
  "Therapeutic session in the studio today. Art heals.",
  "Breaking all the rules with this one. Who says you can't mix these mediums?",
  "Minimalist approach today. Less is more, they say.",
];

const comments = [
  "Absolutely stunning work! The colors are incredible.",
  "This speaks to my soul. Beautiful creation!",
  "I love the texture in this piece. How did you achieve that?",
  "Your best work yet! Keep creating amazing art.",
  "The composition is perfect. Well done!",
  "This is exactly what I needed to see today. Thank you for sharing.",
  "Incredible technique! I'm inspired to try something similar.",
  "The emotion in this piece is palpable. Truly moving.",
  "I could look at this for hours. So many details to discover.",
  "Your use of light and shadow is masterful.",
  "This belongs in a gallery! Seriously impressive.",
  "The color palette is so harmonious. Beautiful choices.",
  "I feel like I'm right there in the scene. Amazing work!",
  "Your style is so unique. I can always recognize your work.",
  "The movement you've captured here is incredible.",
  "This makes me want to pick up my brushes again. Inspiring!",
  "What medium did you use? The finish is gorgeous.",
  "Pure magic! You never cease to amaze me.",
  "The depth in this piece is remarkable. Bravo!",
  "I love how you've interpreted this subject. Fresh perspective!",
  "This is gallery-worthy! Have you considered exhibiting?",
  "The attention to detail is phenomenal. How long did this take?",
  "Your growth as an artist is incredible to witness.",
  "This piece has such a calming energy. Love it!",
  "Bold and beautiful. This is what art is all about.",
  "The contrast in this work is striking. Well executed!",
  "I'm getting strong emotional vibes from this. Powerful stuff.",
  "Your technique gets better with every post. Amazing progress!",
  "This would look perfect in my living room! Is it for sale?",
  "The balance between chaos and order here is perfect.",
  "Simply breathtaking. You have such a gift!",
  "I've been staring at this for 10 minutes. Mesmerizing!",
  "Your creativity knows no bounds. Keep pushing boundaries!",
  "The storytelling in this piece is beautiful.",
  "This captures the essence perfectly. Well done!",
  "I love the experimental nature of this work. So brave!",
  "The textures you've created are incredible to look at.",
  "Art goals right here! You're such an inspiration.",
  "The mood of this piece is absolutely perfect.",
  "Your passion for art really shows through your work.",
];

function getRandomInt(min, max) {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

function getRandomElement(array) {
  return array[Math.floor(Math.random() * array.length)];
}

function shuffleArray(array) {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

async function main() {
  console.log("🌱 Starting database seed...\n");

  // Clear existing data
  console.log("🗑️  Clearing existing data...");
  await prisma.like.deleteMany();
  await prisma.comment.deleteMany();
  await prisma.follow.deleteMany();
  await prisma.post.deleteMany();
  await prisma.user.deleteMany();
  console.log("✅ Existing data cleared\n");

  // Create 50 users
  console.log("👥 Creating 50 users...");
  const hashedPassword = await bcrypt.hash("password123", 10);
  const users = [];

  for (let i = 0; i < 50; i++) {
    const firstName = firstNames[i];
    const lastName = lastNames[i];
    const name = `${firstName} ${lastName}`;
    const email = `${firstName.toLowerCase()}.${lastName.toLowerCase()}@example.com`;

    const user = await prisma.user.create({
      data: {
        email,
        password: hashedPassword,
        name,
        bio: getRandomElement(artistBios),
        profilePicture: `https://i.pravatar.cc/300?u=${email}`,
        bannerImage: getReliableArtImageUrl(i + 500),
        medium: getRandomElement(artMediums),
      },
    });
    users.push(user);
    process.stdout.write(`\r  Created user ${i + 1}/50: ${name}`);
  }
  console.log("\n✅ 50 users created\n");

  // Create posts for each user (10-15 posts each)
  console.log("🎨 Creating posts with artistic images...");
  const allPosts = [];
  let postIndex = 0;

  for (let i = 0; i < users.length; i++) {
    const user = users[i];
    const numPosts = getRandomInt(10, 15);

    for (let j = 0; j < numPosts; j++) {
      const category = getRandomElement(artCategories);
      const title = getRandomElement(postTitles);
      const description = getRandomElement(postDescriptions);

      // Alternate between image sources for variety
      let imageUrl;
      if (postIndex % 3 === 0) {
        imageUrl = getReliableArtImageUrl(postIndex);
      } else if (postIndex % 3 === 1) {
        imageUrl = getPicsumImageUrl(postIndex + 1000);
      } else {
        imageUrl = `https://picsum.photos/seed/art${postIndex}/800/600`;
      }

      const post = await prisma.post.create({
        data: {
          title: `${title} #${postIndex + 1}`,
          description: `${description}\n\n#${category.replace("-", "")} #art #creative #artist`,
          imageUrl,
          tags: `${category},art,creative,${getRandomElement(artMediums).toLowerCase().replace(" ", "")}`,
          medium: getRandomElement(artMediums),
          isProcessPost: Math.random() > 0.8, // 20% chance of being a process post
          authorId: user.id,
          createdAt: new Date(
            Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000,
          ), // Random date within last 90 days
        },
      });
      allPosts.push(post);
      postIndex++;
    }
    process.stdout.write(`\r  Created posts for user ${i + 1}/50`);
  }
  console.log(`\n✅ ${allPosts.length} posts created\n`);

  // Create likes (each post gets 5-30 random likes)
  console.log("❤️  Adding likes to posts...");
  let likeCount = 0;

  for (let i = 0; i < allPosts.length; i++) {
    const post = allPosts[i];
    const numLikes = getRandomInt(5, 30);
    const shuffledUsers = shuffleArray(users);
    const likingUsers = shuffledUsers
      .filter((u) => u.id !== post.authorId)
      .slice(0, numLikes);

    for (const user of likingUsers) {
      try {
        await prisma.like.create({
          data: {
            userId: user.id,
            postId: post.id,
          },
        });
        likeCount++;
      } catch (e) {
        // Skip if duplicate (shouldn't happen but just in case)
      }
    }
    if (i % 50 === 0) {
      process.stdout.write(`\r  Processing post ${i + 1}/${allPosts.length}`);
    }
  }
  console.log(`\n✅ ${likeCount} likes added\n`);

  // Create comments (each post gets 2-10 random comments)
  console.log("💬 Adding comments to posts...");
  let commentCount = 0;

  for (let i = 0; i < allPosts.length; i++) {
    const post = allPosts[i];
    const numComments = getRandomInt(2, 10);
    const shuffledUsers = shuffleArray(users);
    const commentingUsers = shuffledUsers.slice(0, numComments);

    for (const user of commentingUsers) {
      await prisma.comment.create({
        data: {
          content: getRandomElement(comments),
          authorId: user.id,
          postId: post.id,
          createdAt: new Date(
            new Date(post.createdAt).getTime() +
              Math.random() * 7 * 24 * 60 * 60 * 1000,
          ), // Within a week of post
        },
      });
      commentCount++;
    }
    if (i % 50 === 0) {
      process.stdout.write(`\r  Processing post ${i + 1}/${allPosts.length}`);
    }
  }
  console.log(`\n✅ ${commentCount} comments added\n`);

  // Create some follows between users
  console.log("🤝 Creating follow relationships...");
  let followCount = 0;

  for (const user of users) {
    const numFollowing = getRandomInt(5, 20);
    const shuffledUsers = shuffleArray(users);
    const usersToFollow = shuffledUsers
      .filter((u) => u.id !== user.id)
      .slice(0, numFollowing);

    for (const userToFollow of usersToFollow) {
      try {
        await prisma.follow.create({
          data: {
            followerId: user.id,
            followingId: userToFollow.id,
          },
        });
        followCount++;
      } catch (e) {
        // Skip duplicates
      }
    }
  }
  console.log(`✅ ${followCount} follow relationships created\n`);

  // Summary
  console.log("═".repeat(50));
  console.log("🎉 Database seeding completed!");
  console.log("═".repeat(50));
  console.log(`👥 Users: 50`);
  console.log(`🎨 Posts: ${allPosts.length}`);
  console.log(`❤️  Likes: ${likeCount}`);
  console.log(`💬 Comments: ${commentCount}`);
  console.log(`🤝 Follows: ${followCount}`);
  console.log("═".repeat(50));
  console.log("\n📝 Test credentials:");
  console.log("   Email: emma.smith@example.com");
  console.log("   Password: password123");
  console.log("═".repeat(50));
}

main()
  .catch((e) => {
    console.error("❌ Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
